-- En este archivo deben estar tus ejercicios de consultas sql

-- 1. **Empleados ordenados alfabéticamente (Z...A):**  

SELECT APELLIDOS FROM EMPLEADOS
ORDER BY APELLIDOS DESC;
-- Se podría hacer SELECT NOMBRES si quisiese ordenarlos alfabéticamente por nombre.

-- 2. **Empleados de Soporte:**  
SELECT E.NOMBRES, P.PUESTO, L.LOCALIDAD FROM EMPLEADOS E JOIN PUESTOS P ON E.PUESTO_ID = P.ID JOIN DEPARTAMENTOS D ON E.DEPARTAMENTO_ID = D.ID JOIN LOCALIDADES L ON D.LOCALIDAD_ID = L.ID
WHERE P.PUESTO = 'Soporte';

-- 3. **Nombres que terminan con 'o':**  

SELECT NOMBRES FROM EMPLEADOS
WHERE NOMBRES LIKE '%o';

-- 4. **Empleados en Carlos Paz:**  

SELECT E.NOMBRES, E.SUELDO, L.LOCALIDAD FROM EMPLEADOS E JOIN DEPARTAMENTOS D ON E.DEPARTAMENTO_ID = D.ID JOIN LOCALIDADES L ON D.LOCALIDAD_ID = L.ID
WHERE L.LOCALIDAD = 'Carlos Paz';

-- 5. **Sueldos entre 10000 y 13000:**  

SELECT E.NOMBRES, E.SUELDO, L.LOCALIDAD FROM EMPLEADOS E JOIN DEPARTAMENTOS D ON E.DEPARTAMENTO_ID = D.ID JOIN LOCALIDADES L ON D.LOCALIDAD_ID = L.ID
WHERE E.SUELDO BETWEEN 10000 AND 13000;

-- 6. **Departamentos con más de 5 empleados:**  

SELECT D.DENOMINACION, COUNT(E.ID) AS NUM_EMPLEADOS FROM EMPLEADOS E JOIN DEPARTAMENTOS D ON E.DEPARTAMENTO_ID = D.ID
GROUP BY D.ID, D.DENOMINACION
HAVING COUNT(E.ID) > 5;

-- 7. **Empleados en Córdoba con puesto de Analista o Programador:**  

SELECT E.NOMBRES FROM EMPLEADOS E JOIN PUESTOS P ON E.PUESTO_ID = P.ID JOIN DEPARTAMENTOS D ON E.DEPARTAMENTO_ID = D.ID JOIN LOCALIDADES L ON D.LOCALIDAD_ID = L.ID
WHERE L.LOCALIDAD = 'Córdoba' AND P.PUESTO IN ('Analista', 'Programador');

-- 8. **Sueldo medio de todos los empleados:**  

SELECT AVG(SUELDO) AS SUELDO_MEDIO
FROM EMPLEADOS;

-- 9. **Máximo sueldo en el departamento 10:** 

SELECT MAX(SUELDO) AS MAX_SUELDO FROM EMPLEADOS
WHERE DEPARTAMENTO_ID = 10;

-- 10. **Sueldo mínimo en el departamento Soporte:** 

SELECT MIN(E.SUELDO) AS SUELDO_MINIMO FROM EMPLEADOS E JOIN PUESTOS P ON E.PUESTO_ID = P.ID
WHERE P.PUESTO = 'Soporte';

-- 11. **Suma de sueldos por puesto:**  

SELECT P.PUESTO, SUM(E.SUELDO) AS TOTAL_SUELDOS FROM EMPLEADOS E JOIN PUESTOS P ON E.PUESTO_ID = P.ID
GROUP BY P.PUESTO;
